name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.302
        source-url: https://nuget.pkg.github.com/blaised/index.json
      env:
        NUGET_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Add Telerik Nuget source
      run: dotnet nuget add source https://nuget.telerik.com/nuget -n telerik -u ${{ secrets.TELERIK_USERNAME }} -p ${{ secrets.TELERIK_PASSWORD }}

    - name: Set Variables
      run: |
        echo '::set-env name=VERSION_NUMBER::4.0.0'
        echo '::set-env name=REPO::${{ github.repository }}'
        echo '::set-env name=REPO_OWNER::${{ github.repository_owner }}'

    - run: echo '::set-env name=PROJECT_NAME::LogicBuilder.Data'
    - name: Build and Push
      run: ./CI_Build_Push.ps1
      shell: pwsh

    - run: echo '::set-env name=PROJECT_NAME::LogicBuilder.Domain'
    - name: Build and Push
      run: ./CI_Build_Push.ps1
      shell: pwsh

    - run: echo '::set-env name=PROJECT_NAME::LogicBuilder.Structures'
    - name: Build and Push
      run: ./CI_Build_Push.ps1
      shell: pwsh

    - run: echo '::set-env name=PROJECT_NAME::LogicBuilder.Expressions.Utils'
    - name: Build and Push
      run: ./CI_Build_Push.ps1
      shell: pwsh

    - name: Restore
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Test
      run: dotnet test --no-restore --verbosity normal

    - run: echo '::set-env name=PROJECT_NAME::LogicBuilder.Kendo.ExpressionExtensions'
    - name: Pack and push
      run: ./CI_Pack_Push.ps1
      shell: pwsh

    - run: echo '::set-env name=PROJECT_NAME::LogicBuilder.Expressions.EntityFrameworkCore'
    - name: Pack and push
      run: ./CI_Pack_Push.ps1
      shell: pwsh

    - run: echo '::set-env name=PROJECT_NAME::LogicBuilder.EntityFrameworkCore.SqlServer'
    - name: Pack and push
      run: ./CI_Pack_Push.ps1
      shell: pwsh
